"""Seed 20 Lucknow mechanics (10 real + 10 dummy) into the v2 schema."""

from db import get_db, init_db

MECHANICS = [
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+919532934337",
        "workshop_name": "The Car Garage - 24x7 Car Repair",
        "address": "Gomti Nagar, Lucknow",
        "zone": "Gomti Nagar",
        "lat": 26.8520,
        "lng": 81.0050,
        "rating": 4.8,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+918853973725",
        "workshop_name": "GoMechanic - Motor Garage & Repaires",
        "address": "Gomti Nagar, Lucknow",
        "zone": "Gomti Nagar",
        "lat": 26.8430,
        "lng": 80.9960,
        "rating": 4.9,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+917703934785",
        "workshop_name": "Car Medic Motors",
        "address": "Gomti Nagar, Lucknow",
        "zone": "Gomti Nagar",
        "lat": 26.8475,
        "lng": 81.0085,
        "rating": 4.9,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+917703000451",
        "workshop_name": "Bosch Car Service - Shivkunj",
        "address": "Gomti Nagar, Lucknow",
        "zone": "Gomti Nagar",
        "lat": 26.8505,
        "lng": 81.0110,
        "rating": 4.7,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+919319926699",
        "workshop_name": "GoMechanic - Avadh Automobiles",
        "address": "Lalbagh, Lucknow",
        "zone": "Lalbagh",
        "lat": 26.8390,
        "lng": 80.9215,
        "rating": 4.7,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+918853973726",
        "workshop_name": "GoMechanic - Car Workshop (Hazratganj)",
        "address": "Hazratganj, Lucknow",
        "zone": "Hazratganj",
        "lat": 26.8505,
        "lng": 80.9460,
        "rating": 4.8,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+918299281087",
        "workshop_name": "Golden Motor Works",
        "address": "Hazratganj, Lucknow",
        "zone": "Hazratganj",
        "lat": 26.8485,
        "lng": 80.9480,
        "rating": 4.7,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+919838397274",
        "workshop_name": "Car Zone",
        "address": "Hazratganj, Lucknow",
        "zone": "Hazratganj",
        "lat": 26.8460,
        "lng": 80.9505,
        "rating": 4.3,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+919415087864",
        "workshop_name": "Shivam Motors",
        "address": "Alambagh, Lucknow",
        "zone": "Alambagh",
        "lat": 26.8060,
        "lng": 80.9112,
        "rating": 4.3,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Authorized",
        "last_name": "Manager",
        "gender": "prefer_not_to_say",
        "phone_number": "+919472808434",
        "workshop_name": "Mangalam Motors",
        "address": "Alambagh, Lucknow",
        "zone": "Alambagh",
        "lat": 26.8082,
        "lng": 80.9075,
        "rating": 3.2,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Deepak",
        "last_name": "Singh",
        "gender": "male",
        "phone_number": "+919000000001",
        "workshop_name": "Indira Nagar Car Clinic",
        "address": "Indira Nagar, Lucknow",
        "zone": "Indira Nagar",
        "lat": 26.8700,
        "lng": 80.9950,
        "rating": 4.5,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Pradeep",
        "last_name": "Rawat",
        "gender": "male",
        "phone_number": "+919000000002",
        "workshop_name": "Rawat Auto Electricals",
        "address": "Indira Nagar, Lucknow",
        "zone": "Indira Nagar",
        "lat": 26.8730,
        "lng": 80.9920,
        "rating": 4.2,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Kamlesh",
        "last_name": "Patel",
        "gender": "male",
        "phone_number": "+919000000003",
        "workshop_name": "Patel Puncture & Service",
        "address": "Indira Nagar, Lucknow",
        "zone": "Indira Nagar",
        "lat": 26.8680,
        "lng": 80.9980,
        "rating": 4.0,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Harish",
        "last_name": "Chauhan",
        "gender": "male",
        "phone_number": "+919000000004",
        "workshop_name": "Transport Nagar Heavy Works",
        "address": "Transport Nagar, Lucknow",
        "zone": "Transport Nagar",
        "lat": 26.8880,
        "lng": 80.9120,
        "rating": 4.4,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Brijesh",
        "last_name": "Pal",
        "gender": "male",
        "phone_number": "+919000000005",
        "workshop_name": "Pal Diesel & Petrol",
        "address": "Transport Nagar, Lucknow",
        "zone": "Transport Nagar",
        "lat": 26.8860,
        "lng": 80.9090,
        "rating": 4.1,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Aakash",
        "last_name": "Verma",
        "gender": "male",
        "phone_number": "+919000000006",
        "workshop_name": "Chinhat Highway Garage",
        "address": "Chinhat, Lucknow",
        "zone": "Chinhat",
        "lat": 26.8450,
        "lng": 81.0600,
        "rating": 4.3,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Rahul",
        "last_name": "Bajpai",
        "gender": "male",
        "phone_number": "+919000000007",
        "workshop_name": "Bajpai Auto Accessories",
        "address": "Chinhat, Lucknow",
        "zone": "Chinhat",
        "lat": 26.8430,
        "lng": 81.0640,
        "rating": 4.0,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Vivek",
        "last_name": "Tripathi",
        "gender": "male",
        "phone_number": "+919000000008",
        "workshop_name": "Tripathi Car & Bike Works",
        "address": "Chinhat, Lucknow",
        "zone": "Chinhat",
        "lat": 26.8470,
        "lng": 81.0570,
        "rating": 4.2,
        "is_available": False,
        "phone_verified": True,
    },
    {
        "first_name": "Mohit",
        "last_name": "Tiwari",
        "gender": "male",
        "phone_number": "+919000000009",
        "workshop_name": "Lalbagh Express Service",
        "address": "Lalbagh, Lucknow",
        "zone": "Lalbagh",
        "lat": 26.8380,
        "lng": 80.9200,
        "rating": 4.4,
        "is_available": True,
        "phone_verified": True,
    },
    {
        "first_name": "Nitin",
        "last_name": "Chaudhary",
        "gender": "male",
        "phone_number": "+919000000010",
        "workshop_name": "Chaudhary Motor Garage",
        "address": "Lalbagh, Lucknow",
        "zone": "Lalbagh",
        "lat": 26.8360,
        "lng": 80.9230,
        "rating": 4.0,
        "is_available": False,
        "phone_verified": True,
    },
]

UPSERT_SQL = """
INSERT INTO mechanics (
    first_name, last_name, display_name, gender, phone_number, country,
    workshop_name, address, zone, lat, lng, location,
    is_available, rating, phone_verified
)
VALUES (
    %s, %s, %s, %s, %s, 'IN', %s, %s, %s, %s, %s,
    ST_SetSRID(ST_MakePoint(%s, %s), 4326)::geography,
    %s, %s, %s
)
ON CONFLICT (phone_number) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    display_name = EXCLUDED.display_name,
    gender = EXCLUDED.gender,
    workshop_name = EXCLUDED.workshop_name,
    address = EXCLUDED.address,
    zone = EXCLUDED.zone,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    location = EXCLUDED.location,
    is_available = EXCLUDED.is_available,
    rating = EXCLUDED.rating,
    phone_verified = EXCLUDED.phone_verified;
"""


def seed():
    init_db(force_reset=True)

    with get_db() as conn:
        with conn.cursor() as cur:
            for mechanic in MECHANICS:
                display_name = f"{mechanic['first_name']} {mechanic['last_name']}"
                cur.execute(
                    UPSERT_SQL,
                    (
                        mechanic["first_name"],
                        mechanic["last_name"],
                        display_name,
                        mechanic["gender"],
                        mechanic["phone_number"],
                        mechanic["workshop_name"],
                        mechanic["address"],
                        mechanic["zone"],
                        mechanic["lat"],
                        mechanic["lng"],
                        mechanic["lng"],
                        mechanic["lat"],
                        mechanic["is_available"],
                        mechanic["rating"],
                        mechanic["phone_verified"],
                    ),
                )

            cur.execute("SELECT COUNT(*) FROM mechanics;")
            total = cur.fetchone()[0]
            cur.execute(
                "SELECT COUNT(*) FROM mechanics WHERE is_available = TRUE;"
            )
            available = cur.fetchone()[0]

    print(f"{total} mechanics seeded")
    print(f"{available} mechanics with is_available=true")


if __name__ == "__main__":
    seed()
